# Generated by Django 3.0.8 on 2020-07-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('mp3', models.FileField(upload_to='mp3/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('properties', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cluberapp.Music')),
                ('mp4', models.FileField(upload_to='mp4/')),
            ],
        ),
    ]
