# Generated by Django 3.0.8 on 2020-07-22 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cluberapp', '0002_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('properties', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cluberapp.Music')),
                ('url', models.CharField(max_length=120)),
            ],
        ),
    ]
