# Generated by Django 3.0.8 on 2020-07-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluberapp', '0007_auto_20200729_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
