# Generated by Django 3.0.8 on 2020-07-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluberapp', '0009_auto_20200729_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='name',
        ),
    ]
