# Generated by Django 3.0.8 on 2020-07-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluberapp', '0010_remove_album_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='icon',
            field=models.ImageField(default='/static/cluberapp/images/default_icon.svg', upload_to='icons/'),
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default='Unknown', max_length=120),
        ),
    ]
