# Generated by Django 3.0.8 on 2020-07-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluberapp', '0011_auto_20200729_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='icon',
            field=models.ImageField(default='', upload_to='icons/'),
        ),
    ]
