# Generated by Django 3.0.8 on 2020-07-29 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluberapp', '0012_auto_20200729_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='icon',
        ),
    ]
